#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           flip1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           flip2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           flip3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           flip4,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           servo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	int potThreshold = 1616;
	int flipperVal = 0;
	//clearDebugStream;
	//ClearTimer(T1);

	wait1Msec(2000);                // wait 2 seconds before exectuing following code
  bMotorReflected[port2] = true;

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................

		int ch2 = vexRT[Ch2];
		int ch3 = vexRT[Ch3];
		int secondch2 = vexRT[Ch2Xmtr2];
		int secondch3 = vexRT[Ch3Xmtr2];
		int pot = SensorValue[potentiometer];

		//motor[motor1] = motor[motor2] = motor[motor3] = motor[motor10] = ch2;
// Flipper on Controller 2
		/*motor[flip1] = secondch2;
		motor[flip2] = secondch2;
		motor[flip3] = secondch2;
		motor[flip4] = secondch2;*/

		//Flipper button control
		if(vexRT[Btn6UXmtr2])
		{
			motor[servo] = -127;
		}
		if(vexRT(Btn6DXmtr2))
		{
			motor[servo] = 127;
		}


		motor[flip1] = flipperVal;
		motor[flip2] = flipperVal;
		motor[flip3] = flipperVal;
		motor[flip4] = flipperVal;


		if(vexRT[Btn8DXmtr2] && pot < potThreshold) {
			flipperVal = -127;
		} else if (vexRT[Btn8UXmtr2]) {
		flipperVal = 127;
	}else if (pot > potThreshold) {
			flipperVal = -20;
	}  else {
		flipperVal = 0;
	}

	// doesn't work yet

	/*if(vexRT[Btn8DXmtr2] && pot < potThreshold) {
			flipperVal = -127;
		} else if (vexRT[Btn8DXmtr2] && pot > potThreshold) {
			flipperVal = -20;
		} else if (pot > potThreshold && !vexRT[Btn8DXmtr2]) {
			if (pot > 750) {
				flipperVal = 127;
			} else {
			flipperVal = 0;
		}}*/

// Drive On Controller 1
		motor[backLeft] = ch3;
		motor[frontLeft] = ch3;
		motor[backRight] = ch2;
		motor[frontRight] = ch2;

		if(vexRT[Btn7UXmtr2])
		{
			motor[intake] = -127;
		}
		if(vexRT(Btn7DXmtr2))
		{
			motor[intake] = 0;
		}
		if(vexRT[Btn5U]) {
			motor[backLeft] = 127;
			motor[frontLeft] = -127;
			motor[backRight] = -127;
			motor[frontRight] = 127;
	}
	if(vexRT[Btn6U]) {
		motor[backLeft] = -127;
		motor[frontLeft] = 127;
		motor[backRight] = 127;
		motor[frontRight] = -127;
	}

		//int pot = SensorValue[potentiometer];
		//sfoo = time100[T1]/10;
		writeDebugStreamLine("The potentiometer is reading %d", SensorValue[potentiometer]);
		//int shoot vexRT[Btn8D];

		clearLCDLine(0);                                  // clear the top VEX LCD line
    clearLCDLine(1);                                  // clear the bottom VEX LCD line

    setLCDPosition(0,0);                              // set the VEX LCD cursor the first line, first space
    displayNextLCDString("Potentiometer:");           // display "Potentiometer:" on the top line

    setLCDPosition(1,0);                              // set the VEX LCD cursor the second line, first space
    displayNextLCDNumber(SensorValue(potentiometer));







	}
}
